# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

title: Matt WInchell
description: A Collection of Things
author:
  name: Matt Winchell
  email: mattwinchell@gmail.com
  github: HermitCountry
  twitter: HermitCountry
  tumblr: trickybrains
  linkedin: MattWinchell
  bio: Jack of all trades, master of none
  email_md5: fa25185c53dba09506d304c8d94a1492

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH: